apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-30T20:04:05Z"
  generation: 2
  labels:
    app: try2
  name: try2
  namespace: default
  resourceVersion: "1624219"
  uid: 7d87fd88-8cff-4147-80de-8da42bc03361
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: try2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: try2
    spec:
      containers:
      - image: nflondo/public-repo:py_simple_0.1 #pull from docker hub 
        imagePullPolicy: IfNotPresent
        name: simpleapp-01
        readinessProbe:
          periodSeconds: 5 # checks every 5 secs indefinitely
          exec:
            command:
            - cat
            - /tmp/healthy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: goproxy # Adding a sidecar container here as a livenessProve starting here
        image: k8s.gcr.io/goproxy:0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 # End of sidecar container (livenessProbe)
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2021-12-30T20:04:05Z"
    lastUpdateTime: "2021-12-30T20:04:29Z"
    message: ReplicaSet "try2-6bb9d9fc5b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-12-30T20:05:07Z"
    lastUpdateTime: "2021-12-30T20:05:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
